cmake_minimum_required (VERSION 3.22)

project ("NoDesk")
message("Remember to use 'mingw-w64-i686-toolchain'")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -static -static-libgcc -static-libstdc++ -m32")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static -static-libgcc -static-libstdc++ -m32")
# string(APPEND CMAKE_EXE_LINKER_FLAGS "-static -static-libgcc -static-libstdc++")
add_subdirectory(3rdParty)
add_subdirectory(NoDeskCommon)
add_subdirectory(NoDeskRT)
add_subdirectory(NoDesk)
add_subdirectory(NoDeskInstaller)
add_subdirectory(AnyDesk)